# .travis.yml

# specify language
language:
  - python

# specify python version(s)
python:
  - "3.6"
  - "3.7"

# install dependencies
install:
  - pip install -r requirements.txt

# run tests
script:
  -nosetests

TRAVIS_BUILD_DIR:
  flasktaskr/

  